apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfrontend-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microfrontend-1
  template:
    metadata:
      labels:
        app: microfrontend-1
    spec:
      containers:
      - name: microfrontend-1
        image: jorianroelofsen13/microfrontend-1-image:latest  # Update with the correct image name
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microfrontend-1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081  # Change as necessary
  selector:
    app: microfrontend-1
