[book]
authors = ["Jorian Roelofsen"]
language = "nl"
multilingual = false
src = "src"
title = "Een andere kijk op inloggen: Keycloak voor DevOps"

[output.linkcheck]
warning-policy = "ignore"

[output.html.fold]
enable = true
level = 2

[preprocessor.kroki-preprocessor]